jar: QueryApp.jar
local_jar_dir: target/scala-2.10/
remote_jar_dir: /tmp/
main_class: com.adobe.QueryApp
remote_spark_dir: /usr/lib/spark
spark_master: spark://spark_master_server.com:7077
spark_work: /raid/spark-work
